### ISSUE TITLE
Explain commented-out exports of Data.List.Lazy

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-lists#109]
`Data.List.Lazy` contains the exports `some` and `many` commented out: https://github.com/purescript/purescript-lists/blame/master/src/Data/List/Lazy.purs#L19

@garyb added them in the following commit back in 2005: ba68a9bb4e855dcd379994d53c5b19bf72565660

I interpret this as meaning that these are functions that are intended to be at some point added to the API. But I'm not sure.

Can we either add an explanation to these lines to explain why they are commented out, remove them, or write the functions in question and uncomment the lines?

**Comment by matthewleon** [comment]
(closed this because of #27 )

**Comment by garyb** [comment]
The latter would be the preferred option :smile:
