### ISSUE TITLE
use naive Lazy List foldr

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-lists#111]
Currently, Data.List.Lazy defines `foldr` in terms of `foldl` on a `reverse`d list. This preserves stack safety.

Might it be worth sacrificing stack safety to allow `foldr` to work with potentially very large or infinite lists by using the naive definition (trusting the user to use a lazy operation)? If not, is that worth having as a separate function?

Quick example of a consequence of the current def: a function like `traverse_` has to wait until the entire list is traversed before actions can begin.

**Comment by paf31** [comment]
Having a variant of `foldr` which looks like `(a -> Lazy b -> b) -> List a -> b -> b` can be very useful for modularity, or if you're using infinite or lazy lists. Let's add it!

**Comment by matthewleon** [comment]
In the above did you intend to type `forall a b. (a -> Lazy b -> b) -> b -> List a -> b` or are arguments flipped on purpose?

**Comment by matthewleon** [comment]
> Having a variant of foldr which looks like (a -> Lazy b -> b) -> List a -> b -> b can be very useful for modularity, or if you're using infinite or lazy lists. Let's add it!

In the above are arguments flipped on purpose or did you intend `(a -> Lazy b -> b) -> b -> List a -> b`.

**Comment by paf31** [comment]
@matthewleon Shall
