### ISSUE TITLE
replicateM -> replicateA ?

### ISSUE THREAD

**Issue by clayrat** [purescript/purescript-lists#119]
It seems that `Monad` isn't really necessary here, `Applicative` is enough:

```
replicateA :: forall f a. Applicative f => Int -> f a -> f (List a)
replicateA n f
  | n < one = pure nil
  | otherwise = cons <$> x <*> replicateA (n - one) f
```

**Comment by paf31** [comment]
It's defined [here](https://pursuit.purescript.org/packages/purescript-unfoldable/3.0.0/docs/Data.Unfoldable#v:replicateA).

**Comment by MonoidMusician** [comment]
close?

**Comment by paf31** [comment]
Thanks

**Comment by clayrat** [comment]
Hm, I thought about removing this here, or putting a deprecation notice, but I guess I forgot.
