### ISSUE TITLE
Is this actually a lazy left scan?

### ISSUE THREAD

**Issue by drewolson** [purescript/purescript-lists#159]
https://github.com/purescript/purescript-lists/blob/62900a56f6864638c952575dfd211a1cc55be7da/src/Data/List/Lazy.purs#L761

The more I look at this, the more I am convinced that this is a left scan with the args to the function swapped. The following test seems to confirm this:

```purescript
> fromFoldable $ scanrLazy (flip (-)) 10 (1..3)
(9 : 7 : 4 : Nil)
```

I believe I named this incorrectly when submitting the PR. Would love more input from folks who are more experienced.

**Comment by natefaubion** [comment]
Yes, this is a left scan, since you accumulate the head of the list before casing on the tail.
