### ISSUE TITLE
Push v5.4.1 to Pursuit

### ISSUE THREAD

**Issue by JamieBallingall** [purescript/purescript-lists#167]
The latest version shown on Pursuit is 5.4.0 (https://pursuit.purescript.org/packages/purescript-lists/). This causes issues for certain documentation links. Can we push v5.4.1?

**Comment by natefaubion** [comment]
I believe anyone can push docs to pursuit as long as you authenticate.

**Comment by JamieBallingall** [comment]
Ok. I've never done that before. I'll try and figure it out and let you know if I have issues.

**Comment by JamieBallingall** [comment]
I tried to upload to Pursuit using the instructions found at https://pursuit.purescript.org/help/authors.

Having successfully run `pulp login` and received `Successfully authenticated as JamieBallingall.`, I tried `pulp publish` but that resulted in:
```
remote: Permission to purescript/purescript-lists.git denied to JamieBallingall.
fatal: unable to access 'https://github.com/purescript/purescript-lists.git/': The requested URL returned error: 403
* ERROR: Subcommand terminated with exit code 128
```
Do I need to be added to some list of approved users to push docs?

**Comment by hdgarrood** [comment]
No, you just need to use the —no-push flag. That error message comes from trying to push to the GitHub repo.

**Comment by JamieBallingall** [comment]
Ah. Got it.

@natefaubion, @hdgarrood : Thank you for your patient explanations here and on Slack.

Pursuit is now updated. Closing.

**Comment by hdgarrood** [comment]
Thanks!
