### ISSUE TITLE
Add discussion to README, add descriptions to docs

### ISSUE THREAD

**Issue by alexchandel** [purescript/purescript-lists#17]
This module is being proffered as a replacement for `purescript-arrays` in many use cases, but the readme gives no mention of what `purescript-lists` *is*, why it's preferable, or how these types are implemented.

The documentation should at least describe the headline types `ListT`/ `List`/`LazyList`, but mentioning the typical complexity of functions like `head`, `tail`, and `nub` wouldn't hurt either.

**Comment by garyb** [comment]
These points are now covered to some degree in the readme/docs. They can always be improved though!
