### ISSUE TITLE
Do not use `NaturalTransformation` in types of functions that do not preserve the structure

### ISSUE THREAD

**Issue by klntsky** [purescript/purescript-lists#172]
https://github.com/purescript/purescript-lists/commit/04de80b602e6930579a76c48fa8ad2fb5e21498d introduced a change adding NaturalTransformation to types of functions such as `slice`, `head`, etc.

However, as stated in [the docs](https://pursuit.purescript.org/packages/purescript-prelude/4.1.1/docs/Data.NaturalTransformation#t:NaturalTransformation), natural transformation should not manipulate the inner values.

**Comment by hdgarrood** [comment]
These functions don’t manipulate the inner values; they actually aren’t capable of doing so, because the type system prevents that. I think you are understanding “manipulate the inner values” in a different way to how it is meant there.

**Comment by klntsky** [comment]
OK.
