### ISSUE TITLE
Revise groupAllBy to just use an Ordering function

### ISSUE THREAD

**Issue by milesfrain** [purescript/purescript-lists#189]
Proposing we modify the newly-added (in #182) `groupAllBy` from:
```purs
groupAllBy :: forall a. Ord a => (a -> a -> Boolean) -> List a -> List (NEL.NonEmptyList a)
```
to:
```purs
groupAllBy :: forall a. (a -> a -> Ordering) -> List a -> List (NEL.NonEmptyList a)
```
The existing version can lead to undesired output where the `Ord` instance fights against your clustering rule.
The new version also more closely matches the pattern set by these other functions:
```purs
sortBy :: forall a. (a -> a -> Ordering) -> List a -> List a
-- (the below is true after #179)
nubBy :: forall a. (a -> a -> Ordering) -> List a -> List a
```
If we do this before 0.14, we don't even have to worry about an API bump.

@kl0tl for review.

**Comment by hdgarrood** [comment]
Definitely 👍 we made this change already for the same reason in arrays, I think.

**Comment by milesfrain** [comment]
FYI, I'm working on making this change. Don't want to duplicate efforts.

**Comment by JordanMartinez** [comment]
Thanks Miles!
