### ISSUE TITLE
Move to core

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-lists#19]
I'd like to get docs added to these modules and move them to core.

Also:

- Can we implement strict lists in terms of `ListT`? There is a `Lazy` in there right now - does it need to be there or can we add laziness selectively using `Lazy`?
- I still don't understand the use case for the `Skip` constructor in `ListT`. ["`ListT` done right"](https://wiki.haskell.org/ListT_done_right_alternative) in Haskell doesn't need it - is it a laziness issue?

/cc @jdegoes

**Comment by jdegoes** [comment]
>  data ListT f a = ListT (f (Step a (ListT f a)))

This type signature can be lazy if `f` is lazy (without the need to separately introduce `Lazy` in the constructors for `Step`). But we don't have a `LazyT` which basically makes it non-useful for laziness except in the case that `f = Lazy` (at least, as far as I can see). Maybe there's a different way of solving the problem that would allow (1) above.

If you don't use `Skip`, most (all?) of your methods will require `Monad`. Think of a function like `filter` -- how are you going to do that without `Skip` or `Bind`?

**Comment by paf31** [comment]
> If you don't use Skip, most (all?) of your methods will require Monad

Makes sense, thanks.
