### ISSUE TITLE
Make show return "toList [1, 2, 3]" instead of "(Cons 1 (Cons 2 (Cons 3 Nil)))"

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript-lists#43]
I think it would be beneficial to make `show` return `"toList [1, 2, 3]"` instead of `"(Cons 1 (Cons 2 (Cons 3 Nil)))"`, as that's much more readable.

**Comment by jutaro** [comment]
I agree.

**Comment by sharkdp** [comment]
:+1:
