### ISSUE TITLE
Consider renaming fromList, toList

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-lists#50]
I almost always import `Data.List` qualified, like this:

```
import Data.List (List())
import Data.List as List
```

I think this is the best approach, as it makes the code easier to read (you don't have to remember which functions are in scope), and it means that you don't have to be tweaking your imports all the time (which is annoying and decreases the signal-to-noise ratio of diffs).

However it doesn't work very well with `toList` and `fromList`. I think these would be better named `fromFoldable` and `toUnfoldable` respectively; I think they convey the meaning better, and also `List.toList` is a bit redundant. See also purescript/purescript-maps#42.

**Comment by garyb** [comment]
:+1:

**Comment by paf31** [comment]
:+1:
