### ISSUE TITLE
`range` should work on Enums in general.

### ISSUE THREAD

**Issue by chrisdotcode** [purescript/purescript-lists#52]
Currently it only works on `List Int`, when it should be `forall a. (Enum a) => List a`.

**Comment by garyb** [comment]
:+1: when we sort out `Enum` (purescript/purescript-enums#11)

**Comment by garyb** [comment]
Closing this, as we have `enumFromTo` etc. in `purescript-enums` in the end, which can produce any `Unfoldable` type.
