### ISSUE TITLE
Add `toArray` and `fromArray`

### ISSUE THREAD

**Issue by chrisdotcode** [purescript/purescript-lists#53]
For easier conversions back and forth.

**Comment by paf31** [comment]
This is just `fromFoldable` and `toUnfoldable`, right?

**Comment by garyb** [comment]
That's what they should be, but they're named `toList` and `fromList` currently. `purescript-arrays` is missing the `Foldable`/`Unfoldable` conversions though, it'd be handy to have them there.

**Comment by hdgarrood** [comment]
> `purescript-arrays` is missing the `Foldable` / `Unfoldable` conversions

Do you mean `fromFoldable :: forall f a. (Foldable f) => f a -> Array a`, and `toUnfoldable :: forall f a. Array a -> f a`? Why not put those in `arrays`?

**Comment by garyb** [comment]
Yeah, I perhaps wasn't too clear by commenting in here, it was just something I noticed - adding them to `arrays` is what I had in mind.

**Comment by chrisdotcode** [comment]
So is our solution rename `from` and `to` list, or leave them as aliases?

Futhermore, I guess we should open up an issue in `purescript-arrays` about origami - I mean `fold`ing?

**Comment by hdgarrood** [comment]
Yeah, there's #51 already here (but you can use `toList`, `fromList` for now). An issue/PR on `arrays` would probably be good too. I think this can be closed.
