### ISSUE TITLE
Pattern matching does not work

### ISSUE THREAD

**Issue by vstastny** [purescript/purescript-lists#67]
I am not sure why this does not work:

`f :: List Int -> Int`
`f (x : y : _) = x + y`

`g :: List Int -> Int`
`g xs =`
`    case xs of`
`   (h:t) -> h + (g t)`
`   _ -> 0`

In both cases (sorry for formatting in the latter case), this error message is displayed

> Unknown value Data.List.(:)

I would expect this to be working since operator : is in use. Also I understand that head and tail functions were removed from Array due to performance issues. But I though List is a module where such feature should/could be found instead.

**Comment by garyb** [comment]
With the currenlty published version of `purescript-lists`, there is no operator alias defined for the `Cons` constructor, so you'll need to use that for now. There is a function called `(:)`, but that won't allow pattern matching. Or define your own alias locally so you can use patterns like that.

Operator aliases for patterns were only added recently, so the next version of `lists` that is published when we do the update to PureScript 0.9 will have the alias defined.

**Comment by vstastny** [comment]
Aha, the issue is in (:) function which I though should be working like operator alias. By the way, do you know when the 0.9 will take place?

**Comment by garyb** [comment]
Not exactly... we're working on it :wink:

The library updates were supposed to go out for 0.8.x originally, but we couldn't make some required changes in the compiler to go with the new Prelude without causing yet more breaking changes, so it got postponed until 0.9, and now we're trying to get a bunch of breaking changes out of the way before releasing that... it's not been the smoothest release process this time unfortunately.

**Comment by vstastny** [comment]
Ok, thanks for your replies.

**Comment by tbenst** [comment]
I'm still seeing this issue on 0.10.7--is that expected?

**Comment by paf31** [comment]
No, but you need to import the `(:)` alias for `Cons`.

**Comment by tbenst** [comment]
Ah thx! Was missing from https://leanpub.com/purescript/read#leanpub-auto-array-patterns. Will follow up there
