### ISSUE TITLE
ZipList Bind/Monad

### ISSUE THREAD

**Issue by joneshf** [purescript/purescript-lists#72]
If I understand the new programmable type errors, it seems like this instance can be added:

```purescript
instance zipListIsNotBind
  :: Fail "ZipList is not Bind. Any implementation would break the associativity law"
  => Bind ZipList where
    bind = crashWith "bind: unreachable"
```

Also, does this stop the hierarchy? Or can someone take this `Bind` instance and use it to make a `Monad ZipList` and higher instances?

**Comment by paf31** [comment]
Yes, this seems right. Also for things like `V` from `purescript-validation`.

This should prevent anyone from implementing a (non-overlapping) `Monad` instance too.

**Comment by joneshf** [comment]
What about the two questions at the end?

**Comment by paf31** [comment]
I'm not sure exactly what you mean, but this instance should make it impossible to define a non-overlapping `Monad` instance, since any `Monad` instance will need a `Bind` instance too which forces the `Fail` constraint.

**Comment by joneshf** [comment]
Gotcha! Thanks, I'll submit a PR.
