### ISSUE TITLE
Unable to find a suitable version for purescript-eff

### ISSUE THREAD

**Issue by fuzzthink** [purescript/purescript-lists#80]
`bower install purescript-lists --save`

```
...
bower purescript-bifunctors#^2.0.0                   resolved https://github.com/purescript-contrib/purescript-bifunctors.git#2.0.0

Unable to find a suitable version for purescript-eff, please choose one by typing one of the numbers below:
    1) purescript-eff#^1.0.0 which resolved to 1.0.0 and is required by purescript-console#1.0.0
    2) purescript-eff#^2.0.0 which resolved to 2.0.0 and is required by purescript-st#2.0.0

Prefix the choice with ! to persist it to bower.json
```

Can I choose 2 and still use Console? I see the repo has commit saying "preparing for 2.0" , is it ready yet?

**Comment by fuzzthink** [comment]
Selected 2 and reinstall Console to 2.0.

**Comment by garyb** [comment]
You have an old version of `-console` there, which is interfering with the other dependencies. It's worth noting that if you change a `bower.json` but still have stuff left in `bower_components` from a previous set of dependencies it behaves awfully - it's easiest to always delete `bower_components` after changing the dependencies and reinstalling fresh.
