### ISSUE TITLE
guarantee list sorting in type

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-lists#95]
The `insert` function could accept a `SortedList`, whose constructor guarantees sorting, in its type signature. This could perhaps be accompanied by an unsafe constructor for creating a `SortedList` in contexts in which one is confident that the list is sorted.

**Comment by matthewleon** [comment]
Would probably actually also be useful for the type to keep track of the comparison function, allowing insertion into a `SortedList` to maintain the same type.

**Comment by matthewleon** [comment]
Will create a separate repo that tries to add this kind of thing as a separate library.

**Comment by garyb** [comment]
Linking the repo here for future reference: https://github.com/matthewleon/purescript-ordered-lists :smile:
